FROM maven:3.8.8-eclipse-temurin-21 AS builder
WORKDIR /users
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /users
COPY --from=builder /eazybytes-users/target/users-0.0.1-SNAPSHOT.jar users-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "users-0.0.1-SNAPSHOT.jar"]