server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eazybytes_users
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: service-users
  cloud:
    config:
      uri: http://service-main:8888/config
  config:
    import: configserver:http://service-main:8888/config

eureka:
  client:
    service-url:
      defaultZone: http://service-main:8888/eureka
  instance:
    prefer-ip-address: false
    hostname: service-users

security:
  token:
    secret:
      customer: "SECRET_KEY"

management:
  endpoints:
    web:
      exposure:
        include: "*"