server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/eazybytes_users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: service-users
  cloud:
    config:
      uri: http://service-main:8888/config
  config:
    import: configserver:http://service-main:8888/config
  data:
    redis:
      port: 6379
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://service-main:8888/eureka
  instance:
    prefer-ip-address: false
    hostname: service-users

security:
  token:
    secret:
      customer: "SECRET_KEY"

management:
  endpoints:
    web:
      exposure:
        include: "*"