server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybytes_users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: service-users
  cloud:
    config:
      uri: http://localhost:8888/config
  config:
    import: configserver:http://localhost:8888/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: false
    hostname: service-users

security:
  token:
    secret:
      customer: "SECRET_KEY"

management:
  endpoints:
    web:
      exposure:
        include: "*"